### ISSUE TITLE
Create initial version

### ISSUE THREAD

**Issue by akoshunyadi** [camaraproject/DeviceDataVolume#7]
**Problem description**
Initial version of the API(s) should be created, based on https://github.com/camaraproject/APIBacklog/blob/main/documentation/API%20proposals/APIProposal_DeviceDataVolume.md

**Possible evolution**
Provide OAS file(s) 

**Alternative solution**

**Additional context**

**Comment by akoshunyadi** [comment]
I think it would make a sense to first discuss and agree here about general functionality e.g. endpoints and data in & out

**Comment by akoshunyadi** [comment]
As I understand, something like this is required:

**base path: device-data-volume**

**POST /retrieve**
Request: 
- device  

Response:
- enum of predefined volume categories (e.g. <200MB, <1GB, <5GB, >=5GB)
 
**POST /subscriptions**
Request:
- device
- enum of predefined volume categories, when changing to the specific cat: (e.g. <200MB, <1GB, <5GB, >=5GB) or on all changes

**Questions:**
- Do we need percentual value in the response?
- Do we need the booked volume in the response?
- Do we need a free volume value in the request to check against?
- Do we need 3-legged auth?

**Comment by sachinvodafone** [comment]
Hi All,  I need some scope clarification on a scenario where the user has multiple active data plans, such as a 4-hour time-bound package purchased within a specific timeframe and a separate 5GB mobile data plan, how should the API manage notifications?

- Should the user receive separate notifications for each plan ?
- Should there be a single, unified notification summarizing both plans?

**Comment by bigludo7** [comment]
Hello
Another idea here. Can we think also about an check operation? In this case the requester will provide device identifier and data volume to be checked. The answer will just provide a boolean to indicate if remaining data volume is above this volume to be checked.

I propose this because, first, it is less sensitive on user data to be provided and second because we imagine UC where the app developer wants to check before an update, a download or a session that there is enough data credit on the line to trigger it.

**Comment by akoshunyadi** [comment]
@bigludo7 I agree, a check against an input value is the most flexible solution and it doesn't expose additional (sensitive) information.
